
# JPA
server.port=${SPRING_PORT:8080}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_7uWuV8zaJ}
core.api.url=${CORE_URL:http://localhost:8081}
sqs.process=${SQS_PROCESS:https://sqs.us-east-1.amazonaws.com/783545975704/video-processing-queue}
s3.bucket=${S3_BUCKET_NAME:fiapfase5-user-video-uploads}
s3.bucket.download=${S3_DOWNLOAD_BUCKET:fiapfase5-processed-videos}

