apiVersion: v1
kind: ServiceAccount
metadata:
  name: video-api-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::783545975704:role/video-api-irsa-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-api
  labels:
    app: video-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-api
  template:
    metadata:
      labels:
        app: video-api
    spec:
      serviceAccountName: video-api-sa
      containers:
      - name: video-api
        image: 783545975704.dkr.ecr.us-east-1.amazonaws.com/video-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: COGNITO
          value: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_YrVoG2lcU"
        - name: CORE_URL
          value: "http://core-api-service.default.svc.cluster.local"
        - name: SQS_PROCESS
          value: "https://sqs.us-east-1.amazonaws.com/783545975704/video-processing-queue"
        - name: S3_BUCKET_NAME
          value: "fiapfase5-user-video-uploads"
        - name: S3_DOWNLOAD_BUCKET
          value: "fiapfase5-processed-videos"
---
apiVersion: v1
kind: Service
metadata:
  name: video-api-service
spec:
  selector:
    app: video-api
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP